% AUTO-GENERATED by module/contracts/goal_formula_check.py's
% generate_safety_queries -- DO NOT HAND-EDIT, this is derived
% entirely from the problem's own behavior_tree.xml (via
% bt_to_prolog.py) and regenerated by main.py before every run.

query(verify_goal_formula).
query(plan_outcome(true)).
query(plan_outcome(false)).
query(plan_outcome(world_too_large)).
query(plan_outcome(reactive_escaped)).
query(outcome_signature(_)).

query(any_reason_pattern(battery_depleted)).
query(any_reason_pattern(completed)).
query(any_reason_pattern(completed(straight,point(11.675,11.525)))).
query(any_reason_pattern(crashed(wild))).
query(any_reason_pattern(no_path(straight,point(11.675,11.525)))).

query(any_reason_pattern_by_action(completed(straight,point(11.675,11.525)),a1)).
query(any_reason_pattern_by_action(no_path(straight,point(11.675,11.525)),a1)).
query(any_reason_pattern_by_action(completed,a2)).
query(any_reason_pattern_by_action(crashed(wild),a2)).
query(any_reason_pattern_detail_by_action(crashed(_),a2)).
query(any_reason_pattern_by_action(battery_depleted,a2)).

query(any_condition_status(c1,true)).
query(any_condition_status(c1,false)).
