% AUTO-GENERATED by module/contracts/goal_formula_check.py's
% generate_safety_queries -- DO NOT HAND-EDIT, this is derived
% entirely from the problem's own behavior_tree.xml (via
% bt_to_prolog.py) and regenerated by main.py before every run.

query(verify_goal_formula).
query(plan_outcome(true)).
query(plan_outcome(false)).
query(plan_outcome(world_too_large)).
query(plan_outcome(reactive_escaped)).
query(outcome_signature(_)).



