% AUTO-GENERATED by occgrid_to_problog.py -- do not hand-edit.
% Source map: /home/user/BT_project/problems/problem2/map.yaml
% obstacle_polygon(Id, [point(X,Y), ...]) -- vertices in metres,
% map frame, consistent with the source OccupancyGrid's origin.
% 12 obstacle region(s) extracted.

obstacle_polygon(obs1, [point(13.9000,4.2000), point(13.8000,4.1500), point(13.7500,3.9000), point(13.8000,3.8000), point(14.0500,3.7500), point(14.1500,3.8000), point(14.2000,4.0500), point(14.1500,4.1500)]).
obstacle_polygon(obs2, [point(8.9000,4.2000), point(8.8000,4.1500), point(8.7500,3.9000), point(8.8000,3.8000), point(9.0500,3.7500), point(9.1500,3.8000), point(9.2000,4.0500), point(9.1500,4.1500)]).
obstacle_polygon(obs3, [point(3.9000,4.2000), point(3.8000,4.1500), point(3.7500,3.9000), point(3.8000,3.8000), point(4.0500,3.7500), point(4.1500,3.8000), point(4.2000,4.0500), point(4.1500,4.1500)]).
obstacle_polygon(obs4, [point(13.9000,7.2000), point(13.8000,7.1500), point(13.7500,6.9000), point(13.8000,6.8000), point(14.0500,6.7500), point(14.1500,6.8000), point(14.2000,7.0500), point(14.1500,7.1500)]).
obstacle_polygon(obs5, [point(8.9000,7.2000), point(8.8000,7.1500), point(8.7500,6.9000), point(8.8000,6.8000), point(9.0500,6.7500), point(9.1500,6.8000), point(9.2000,7.0500), point(9.1500,7.1500)]).
obstacle_polygon(obs6, [point(3.9000,7.2000), point(3.8000,7.1500), point(3.7500,6.9000), point(3.8000,6.8000), point(4.0500,6.7500), point(4.1500,6.8000), point(4.2000,7.0500), point(4.1500,7.1500)]).
obstacle_polygon(obs7, [point(13.9000,10.2000), point(13.8000,10.1500), point(13.7500,9.9000), point(13.8000,9.8000), point(14.0500,9.7500), point(14.1500,9.8000), point(14.2000,10.0500), point(14.1500,10.1500)]).
obstacle_polygon(obs8, [point(8.9000,10.2000), point(8.8000,10.1500), point(8.7500,9.9000), point(8.8000,9.8000), point(9.0500,9.7500), point(9.1500,9.8000), point(9.2000,10.0500), point(9.1500,10.1500)]).
obstacle_polygon(obs9, [point(3.9000,10.2000), point(3.8000,10.1500), point(3.7500,9.9000), point(3.8000,9.8000), point(4.0500,9.7500), point(4.1500,9.8000), point(4.2000,10.0500), point(4.1500,10.1500)]).
obstacle_polygon(obs10, [point(13.9000,13.2000), point(13.8000,13.1500), point(13.7500,12.9000), point(13.8000,12.8000), point(14.0500,12.7500), point(14.1500,12.8000), point(14.2000,13.0500), point(14.1500,13.1500)]).
obstacle_polygon(obs11, [point(8.9000,13.2000), point(8.8000,13.1500), point(8.7500,12.9000), point(8.8000,12.8000), point(9.0500,12.7500), point(9.1500,12.8000), point(9.2000,13.0500), point(9.1500,13.1500)]).
obstacle_polygon(obs12, [point(3.9000,13.2000), point(3.8000,13.1500), point(3.7500,12.9000), point(3.8000,12.8000), point(4.0500,12.7500), point(4.1500,12.8000), point(4.2000,13.0500), point(4.1500,13.1500)]).
